# global NEURONS_PER_CORE, CORES_PER_CHIP, NEURONS_PER_CHIP, MAX_NUM_CAMS, NUM_CHIPS

NEURONS_PER_CORE = 256
CORES_PER_CHIP = 4
NEURONS_PER_CHIP = NEURONS_PER_CORE * CORES_PER_CHIP
MAX_NUM_CAMS = 64
NUM_CHIPS = 4

ADDR_NUM_BITS = 15
ISI_NUM_BITS = 16
MAX_ISI = 2**ISI_NUM_BITS-1
MAX_FPGA_LEN = 2**ADDR_NUM_BITS-1
